/**
 * The reference instance's vocabulary (wikibase.ronzz.org, verified
 * 2026-08-30), as the wbgetentities response the resolver expects. Kept in
 * step with the DEFAULT_* tables in
 * src/tools/extensions/embeddable-content/embeddableVocabulary.ts — a drift
 * between the two fails the vocabulary tests on purpose.
 */
export const VOCABULARY_ENTITIES: Record<
	string,
	{ id: string; labels: { en: { value: string } } }
> = {
	P1: { id: 'P1', labels: { en: { value: 'instance of' } } },
	P2: { id: 'P2', labels: { en: { value: 'content text' } } },
	P3: { id: 'P3', labels: { en: { value: 'code source' } } },
	P4: { id: 'P4', labels: { en: { value: 'LaTeX source' } } },
	P5: { id: 'P5', labels: { en: { value: 'programming language' } } },
	P6: { id: 'P6', labels: { en: { value: 'attributed to' } } },
	P7: { id: 'P7', labels: { en: { value: 'source URL' } } },
	P8: { id: 'P8', labels: { en: { value: 'date' } } },
	P12: { id: 'P12', labels: { en: { value: 'Wikidata ID' } } },
	P13: { id: 'P13', labels: { en: { value: 'ORCID' } } },
	P14: { id: 'P14', labels: { en: { value: 'VIAF ID' } } },
	P15: { id: 'P15', labels: { en: { value: 'ISNI' } } },
	P16: { id: 'P16', labels: { en: { value: 'DOI' } } },
	P17: { id: 'P17', labels: { en: { value: 'ISBN-13' } } },
	P18: { id: 'P18', labels: { en: { value: 'OpenAlex Work ID' } } },
	P19: { id: 'P19', labels: { en: { value: 'PubMed ID' } } },
	P24: { id: 'P24', labels: { en: { value: 'page(s)' } } },
	P25: { id: 'P25', labels: { en: { value: 'volume' } } },
	P26: { id: 'P26', labels: { en: { value: 'issue' } } },
	P28: { id: 'P28', labels: { en: { value: 'source' } } },
	P29: { id: 'P29', labels: { en: { value: 'describes' } } },
	P30: { id: 'P30', labels: { en: { value: 'implementation of' } } },
	P33: { id: 'P33', labels: { en: { value: 'developer' } } },
	P34: { id: 'P34', labels: { en: { value: 'license' } } },
	P35: { id: 'P35', labels: { en: { value: 'operating system' } } },
	P36: { id: 'P36', labels: { en: { value: 'official website' } } },
	P37: { id: 'P37', labels: { en: { value: 'source code repository' } } },
	P39: { id: 'P39', labels: { en: { value: 'has use' } } },
	P41: { id: 'P41', labels: { en: { value: 'user interface' } } },
	P43: { id: 'P43', labels: { en: { value: 'documentation URL' } } },
	P44: { id: 'P44', labels: { en: { value: 'part of' } } },
	P45: { id: 'P45', labels: { en: { value: 'duration' } } },
	P46: { id: 'P46', labels: { en: { value: 'YouTube channel ID' } } },
	P47: { id: 'P47', labels: { en: { value: 'YouTube video ID' } } },
	P48: { id: 'P48', labels: { en: { value: 'URL' } } },
	P49: { id: 'P49', labels: { en: { value: 'chapters' } } },
	P50: { id: 'P50', labels: { en: { value: 'date of birth' } } },
	P51: { id: 'P51', labels: { en: { value: 'place of birth' } } },
	P52: { id: 'P52', labels: { en: { value: 'date of death' } } },
	P53: { id: 'P53', labels: { en: { value: 'place of death' } } },
	P54: { id: 'P54', labels: { en: { value: 'publisher (entity)' } } },
	P55: { id: 'P55', labels: { en: { value: 'access URL' } } },
	P57: { id: 'P57', labels: { en: { value: 'journal (entity)' } } },
	P58: { id: 'P58', labels: { en: { value: 'OpenAlex author ID' } } },
	P59: { id: 'P59', labels: { en: { value: 'present in work' } } },
	P60: { id: 'P60', labels: { en: { value: 'parent organization' } } },
	Q2: { id: 'Q2', labels: { en: { value: 'quotation content' } } },
	Q3: { id: 'Q3', labels: { en: { value: 'code snippet' } } },
	Q4: { id: 'Q4', labels: { en: { value: 'mathematical expression' } } },
	Q6: { id: 'Q6', labels: { en: { value: 'person' } } },
	Q7: { id: 'Q7', labels: { en: { value: 'organization' } } },
	Q8: { id: 'Q8', labels: { en: { value: 'group of humans' } } },
	Q9: { id: 'Q9', labels: { en: { value: 'book' } } },
	Q10: { id: 'Q10', labels: { en: { value: 'scholarly article' } } },
	Q11: { id: 'Q11', labels: { en: { value: 'website' } } },
	Q12: { id: 'Q12', labels: { en: { value: 'song' } } },
	Q13: { id: 'Q13', labels: { en: { value: 'film' } } },
	Q14: { id: 'Q14', labels: { en: { value: 'video' } } },
	Q179: { id: 'Q179', labels: { en: { value: 'free and open-source software' } } },
	Q337: { id: 'Q337', labels: { en: { value: 'YouTube channel' } } },
	Q338: { id: 'Q338', labels: { en: { value: 'YouTube video' } } },
	Q339: { id: 'Q339', labels: { en: { value: 'web page' } } },
	Q340: { id: 'Q340', labels: { en: { value: 'book excerpt' } } },
	Q341: { id: 'Q341', labels: { en: { value: 'private company' } } },
	Q342: { id: 'Q342', labels: { en: { value: 'public company' } } },
	Q343: { id: 'Q343', labels: { en: { value: 'non-profit organization' } } },
	Q344: { id: 'Q344', labels: { en: { value: 'governmental agency' } } },
	Q345: { id: 'Q345', labels: { en: { value: 'music band' } } },
	Q346: { id: 'Q346', labels: { en: { value: 'educational institution' } } },
	Q347: { id: 'Q347', labels: { en: { value: 'research institute' } } },
	Q348: { id: 'Q348', labels: { en: { value: 'political party' } } },
	Q349: { id: 'Q349', labels: { en: { value: 'trade union' } } },
	Q350: { id: 'Q350', labels: { en: { value: 'religious organization' } } },
	Q351: { id: 'Q351', labels: { en: { value: 'sports team' } } },
	Q364: { id: 'Q364', labels: { en: { value: 'fictional character' } } },
};

export function vocabularyRequestResponse(): { entities: typeof VOCABULARY_ENTITIES } {
	return { entities: VOCABULARY_ENTITIES };
}
